INSERT INTO EpicWildQuest.stories (id, story, creatures_id, locations_id, type) VALUES (1, 'Vous vous réveillez dans une chambre de taverne, la bouche pâteuse, l’esprit embrouillé. La soirée a été compliquée n’est-ce pas ? Dépité, vous vous souvenez que vous avez dépensé toutes vos économies en bière, quel dommage. Un pop sonore provenant de la grande salle vous extirpe de vos pensées. De nature curieuse mais subissant encore vos excès de la veille vous hésitez entre aller voir ce qui se passe ou vous rendormir. Après tout, vous avez payé cette chambre.', null, 1, 'Story');
INSERT INTO EpicWildQuest.stories (id, story, creatures_id, locations_id, type) VALUES (2, 'Vous avez préféré mettre votre curiosité de côté, tant pis pour vous. Vous vous rendormez pour ne plus jamais vous réveiller, en d’autres termes, vous êtes mort.', null, 1, 'Dead');
INSERT INTO EpicWildQuest.stories (id, story, creatures_id, locations_id, type) VALUES (3, 'S’extirper du confort de votre lit n’a pas été chose facile mais vous y êtes parvenu ! En descendant les marches, vous remarquez des choses étranges. En effet, les affiches placardées aux murs sont écrites dans un langage que vous n’arrivez pas à déchiffrer. Plus vous regardez ces affiches, plus vous avez du mal à avancer. Vos jambes deviennent lourdes, vous êtes paralysé. Une voix grave vous explique que vous êtes sous l’emprise d’un sortilège, le seul moyen de vous en sortir est de traduire les affiches.', null, 2, 'Enigma');
INSERT INTO EpicWildQuest.stories (id, story, creatures_id, locations_id, type) VALUES (4, 'Un mage vous a lancé ce sortilège pour tester votre étoffe de héro. Malheureusement cet encerclement n’a qu’une seule issue que vous n’arrivez pas à résoudre. Vous tombez dans un état végétatif, vous mourrez de soif au bout de trois jours.', null, 2, 'Dead');
INSERT INTO EpicWildQuest.stories (id, story, creatures_id, locations_id, type) VALUES (5, '- Bien joué ! Vous avez l’étoffe d’un héro !
Vous tombez nez à nez avec un homme âgé. D’après sa tenue, vous en déduisez que c’est un mage et que c’est surement lui qui vous a ensorcelé.
- Je vous prie de m’excuser pour ce tour de passe-passe. Le royaume est en perdition, je me devais de vérifier vos capacités.
Le mage vous explique qu’un sorcier maléfique a créé une machine perturbant le langage du royaume. Il vous engage pour le tuer et détruire son infernale création. Votre chemin sera semé d’embuche, car le sorcier a de nombreux serviteurs et a posé divers pièges afin que personne ne puisse l''atteindre. La somme d’argent que vous propose le mage étant conséquente, vous acceptez.(Warrior 20 gold, Mage 50 gold, Rogue 100) Il vous propose deux chemins pour rejoindre le château du sorcier. Passer par la forêt ou par le marécage.', null, 2, 'Story');
INSERT INTO EpicWildQuest.stories (id, story, creatures_id, locations_id, type) VALUES (6, 'Cela fait une heure que vous avez quitté la taverne, vous n’avez croisé personne et vous commencez à croire que cette mission sera des plus simple. Vous êtes tellement à l’aise que vous sifflez gaiement pensant à l’argent facile que vous venez d’obtenir et aux bières que vous vous payerez. Soudainement vous entendez un grognement et vous vous retournez. Un loup féroce vous fonce dessus. Vous n’êtes pas du genre à fuir, vous vous engagez dans le combat.', 1, 3, 'Fight');
INSERT INTO EpicWildQuest.stories (id, story, creatures_id, locations_id, type) VALUES (7, 'Vous vous sentez mal, l’ambiance pesante du marécage vous rend mal à l’aise. Cette mission ne sera peut-être pas des plus simples. Vous finissez par tomber sur un pont surplombant un étang. Vous décidez de faire une petite pause. A peine vous êtes vous approché du bord de l’eau qu’une créature mi-crapaud, mi-homme tente de vous entraîner dans le fond. Vous devez remercier vos réflexes car ils vous ont empêché d''être happé dans les eaux boueuses. La créature sort de l’eau pour vous attaquer. Vous n’êtes pas du genre à fuir, vous vous engagez dans le combat.', 2, 4, 'Fight');